apiVersion: apps/v1
kind: Deployment
metadata:
  name: rose-game-ai
  labels:
    app: rose-game-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rose-game-ai
  template:
    metadata:
      labels:
        app: rose-game-ai
    spec:
      containers:
      - name: rose-game-ai
        image: quay.io/rose/rose-game-ai:latest  # Modify with your Docker image name and tag.
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: rose-game-ai
spec:
  selector:
    app: rose-game-ai
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
